version: '3.4'

services:
    eshopdb:
        image: postgres

    distributedcache:
        image: redis

    seq:
        image: datalust/seq:latest

    messagebus:
        image: rabbitmq:3-management

volumes:
    postgres_eshopdb:

