version: '3.4'

services:
    eshopdb:
        image: postgres

    distributedcache:
        image: redis

    seq:
        image: datalust/seq:latest

    messagebus:
        image: rabbitmq:3-management

    identity:
        image: quay.io/keycloak/keycloak:latest

    api:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: Boostrapper/Api/Dockerfile

volumes:
    postgres_eshopdb:


